AlwaysEncryptedSample/Controllers/CreditCardsController.cs
using System;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using AlwaysEncryptedSample.Models;

namespace AlwaysEncryptedSample.Controllers
{
    /// <summary>
    /// CRUD Operations for the credit card table.
    /// </summary>
    [Authorize(Roles="Credit Card Admins")]
    public sealed class CreditCardsController : ControllerBase
    {
        /// <summary>
        /// Import credit card data from a server side CSV
        /// </summary>
        /// <returns>Redirects to the Credit Card List</returns>
        /// <remarks>
        /// Very optomistic parsing because we are importing a static file we can trust.
        /// However, no bulk insert is happening.
        /// </remarks>
        public ActionResult Import()
        {
            //TODO: This might be slow according to dead link here.
            // http://stackoverflow.com/questions/697339/accessing-file-in-app-data-from-a-class-in-the-app-code-folder
            var csvFile = Path.Combine
                (HttpContext.ApplicationInstance.Request.PhysicalApplicationPath,
                 "App_Data", "CreditCards.csv");

            using (var file = System.IO.File.Open(csvFile, FileMode.Open, FileAccess.Read))
            using (var rdr = new StreamReader(file))
            {
                rdr.ReadLine(); // throw out headers
                var line = rdr.ReadLine();
                while (line != null)
                {
                    var fields = line.Split(',');
                    var cc = _appContext.CreditCards.Create();
                    cc.CardNumber = fields[0];
                    cc.ExpYear = short.Parse(fields[1]);
                    cc.ExpMonth = byte.Parse(fields[2]);
                    cc.CCV = short.Parse(fields[3]);
                    cc.Network = _appContext.CreditCardNetworks.ToList().First
                        (ccn => ccn.Id == (CreditCardNetworks) Enum.Parse(typeof(CreditCardNetworks), fields[4]));
                    _appContext.CreditCards.Add(cc);
                    line = rdr.ReadLine();
                }
                _appContext.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Index()
        {
            return View(_appContext.CreditCards.ToList());
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            var cc = _appContext.CreditCards.Find(id);
            if (cc == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.NotFound);
            }
            _appContext.CreditCards.Remove(cc);
            _appContext.SaveChanges();
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.OK);
        }

    }
}

AlwaysEncryptedSample/Controllers/InternalsController.cs
using System.Linq;
using System.Reflection;
using System.Resources;
using System.Web.Mvc;
using AlwaysEncryptedSample.Models;

namespace AlwaysEncryptedSample.Controllers
{
    /// <summary>
    /// Internals for the DBA to see
    /// </summary>
    [Authorize(Roles="DBAs")]
    public sealed class InternalsController : ControllerBase
    {
        private ResourceManager _rm = new ResourceManager("AlwaysEncryptedSample.Properties.Resources", Assembly.GetExecutingAssembly());

        public ActionResult Index()
        {
            var sql = _rm.GetString("EncryptedColumnsSQL");
            var columns = _appContext.Database.SqlQuery<ColumnInfo>(sql);

            return View(columns.ToList());
        }
    }
}

AlwaysEncryptedSample/Views/Shared/_Layout.cshtml
@using Microsoft.Ajax.Utilities
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryajax")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Always Encrypted Sample", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if(User.IsInRole("Credit Card Admins")){<li>@Html.ActionLink("Credit Cards", "Index", "CreditCards")</li>}
                    @if(User.IsInRole("DBAs")){<li>@Html.ActionLink("DB Columns", "Index", "Internals")</li>}
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Microsoft Corporation</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>